# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Loom 1.17 is not yet compatible with IntelliJ IDEA configuration cache.
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.6
maven_group=org.karn
archives_base_name=KoreanChat

# Dependencies
fabric_api_version=0.158.0+26.2
player_data_api_version=0.11.0+26.2
